### ISSUE TITLE
Linking MariaDB

### ISSUE THREAD

**Issue by EtienneBruines** [diegomarangoni/docker-mariadb-galera#1]
Hi,

First-off: nice image. 

Secondly, I was wondering *why* you're removing `/var/lib/mysql`, and making users link it when running the container? What's the point in that?

Also, [line 20](https://github.com/diegomarangoni/docker-mariadb-galera/blob/master/Dockerfile#L20) looks a lot like line 18.

**Comment by EtienneBruines** [comment]
My mistake... This is to allow for persistent storage.

**Comment by diegomarangoni** [comment]
Hi @EtienneBruines 

The line 20 was there by mistake, I've just removed and sent a commit.

Thanks for your contribution.
