### ISSUE TITLE
WSREP: Some threads may fail to exit.

### ISSUE THREAD

**Issue by Nasjoe** [diegomarangoni/docker-mariadb-galera#2]
Hi !

Many thanks for your work. I search a similar solution and i'm very happy that your git exist :)

I have a issue when i follow your tutoriel.
Here's my run :

#node1 :
docker run \
    -v /galeraclustermysql/my.cnf:/etc/mysql/my.cnf \
    -v /MYSQL/data:/var/lib/mysql \
    -e MYSQL_ROOT_PASSWORD="yeah" \
    --name node1 \
    -h node1 \
    diegomarangoni/mariadb-galera

#node2 :
docker run \
    -v /galeraclustermysql/my.cnf:/etc/mysql/my.cnf \
	--volumes-from node1 \
    -e MYSQL_ROOT_PASSWORD="yeah" \
    --name node2 \
    -h node2 \
    --link node1:node1 \
    diegomarangoni/mariadb-galera

here the my.cnf : 
[mysqld]
datadir=/var/lib/mysql
socket=/var/run/mysqld/mysqld.sock
user=mysql
binlog-format=ROW
default-storage-engine=InnoDB
innodb-autoinc-lock-mode=2
innodb-flush-log-at-trx-commit=0
innodb-buffer-pool-size=122M
innodb-doublewrite=1
innodb-flush-method=O_DIRECT
wsrep-provider=/usr/lib/galera/libgalera_smm.so
wsrep-cluster-name=my_super_cluster
wsrep-sst-method=rsync
query-cache-size=524288
log-error=/dev/stderr

[mysql_safe]
log-error=/dev/stderr
pid-file=/var/run/mysqld/mysqld.pid

After the run, the both say : "Waiting for instructions..."
Docker say that ip are node1 :  172.17.0.53 and node 2 : 172.17.0.54

so i launch the first echo : 
echo "mysqld --wsrep-new-cluster --wsrep-cluster-address=gcomm://172.17.0.53,172.17.0.54" | nc 172.17.0.53 13306

here's the log : http://paste.ubuntu.com/12858556/

and the second echo : 
echo "mysqld --wsrep-cluster-address=gcomm://172.17.0.53,172.17.0.54" | nc 172.17.0.54 13306

and here's the log : http://paste.ubuntu.com/12858564/

As you can see, the node2 can't connect to the master.

"
151019  8:19:21 [Note] WSREP: New cluster view: global state: :-1, view# 0: Primary, number of nodes: 1, my index: 0, protocol version 3
151019  8:19:21 [ERROR] WSREP: SST failed: 1 (Operation not permitted)
151019  8:19:21 [ERROR] Aborting

"

Did you have any idea ?

Many thanks !
Jonas.

**Comment by diegomarangoni** [comment]
Hey @Nasjoe thanks for reporting!

Did you generated the SSL certificates?
Replicator needs it to communicate with each other, that's why WSREP failed.

Try to use a certificate and let me know if it works.

**Comment by diegomarangoni** [comment]
If you still have this problem, please, reopen the ticket.
